### ISSUE TITLE
How to display the depth image or depth pointcloud only?

### ISSUE THREAD

**Issue by Cynthia0217** [code-iai/iai_kinect2#147]
Hi, I am new to Kinect 2.0 and ROS. Now I face a problem, After calibration, using Kinect_viewer I can obtain image and pointcloud images succesfully, the problem is I don't know the  mode: 'qhd', 'hd', 'sd' or 'ir' exactly stands for what kind of image. If I want to obtain the depth image only (not superimposed on the RGB image), how can I get one?

Thanks a lot!

**Comment by wiedemeyer** [comment]
The `kinect2_viewer` has no option to only show the depth image. For viewing single image streams you could use `image_view`, but it might not work for 16 bit depth images.
The modes are different resolutions, for details look at the documentation of `kinect2_bridge`. And ir uses the IR image instead of the color image.

**Comment by Cynthia0217** [comment]
@wiedemeyer Thank you for explanation. Best Regards~
