### ISSUE TITLE
Should I rotate the cloud after subscribing the ROS topic?

### ISSUE THREAD

**Issue by MarcoFierimonte** [code-iai/iai_kinect2#180]
Hi,

I'd like to create a personal ROS TF  tree but I don't understand very well how works coordinates systems between iai_kinect2 and PCL.
For istance:
1) if I subscribe to "kinect2/sd/points" topic, my ROS callback will receive a  sensor_msgs::PointCloud2 message. 
2) After that I use pcl::fromROSMsg() to convert the message in a pcl::PointCloud<pcl::PointXYZRGB> object.
3) I do some processing on the cloud
4) Finally I convert the cloud in a sensor_msgs::PointCloud2 using pcl::toROSMsg() and publish it on a ROS topic.

Why after point 2) if I use a pcl viewer to show the cloud is inverted? Have I to rotate the cloud using something like pcl::transformPointCloud () ?	

Thanks in advance :)

**Comment by wiedemeyer** [comment]
What do you mean with inverted? How does it look in rviz?

**Comment by MarcoFierimonte** [comment]
In rviz I look the same of the pcl viewer, the point cloud is upside down. Insteed if I use your iai_kinect2 viewer is correct. Also with the ./Protonect viewer is correct. Maybe it's because the coordinates systems between the kinect V2 and ROS are different? 

Thanks for your help.

**Comment by wiedemeyer** [comment]
Hi,
I looked at rviz and it looked totally fine, nothing is inverted. If you mean, why the point cloud in rviz is projected along the `z` axis, in other words "projected into the sky". This is because no transform for given for `kinect2_link`. In rviz `z` is pointing up, therefore the point cloud is projected that way.

**Comment by MarcoFierimonte** [comment]
Hi,

I don't understand if your kinect2_viewer do some rotation of the point cloud. Because using it I have: 
![kinect2_viewer_sd_cloud](https://cloud.githubusercontent.com/assets/12981741/11215309/d83fc478-8d45-11e5-89eb-30fb01504eaf.png)

instead using my simple viewer I obtain the point cloud upside down:
![my_cloud_viewer_sd_cloud_1](https://cloud.githubusercontent.com/assets/12981741/11215355/f9bbd86c-8d45-11e5-898a-9566fdc5ebd1.png)

finally with RVIZ: 
![rviz_sd_cloud_1](https://cloud.githubusercontent.com/assets/12981741/11215378/0f447df6-8d46-11e5-8325-774f4fe02034.png)

Is this result correct? Should I rotate the cloud obtained from "/kinect2/sd/points"?

**Comment by wiedemeyer** [comment]
Looks just right. z is the depth, x is from left to right and y is from top to bottom. That is like the coordinates are defined for images. The problem is, that the default camera rotation is the pcl viewer and Rviz is different. You just have to change the camera rotation by rotation it around z by 180 degree. That is what I did in the kinect2_viewer.

**Comment by MarcoFierimonte** [comment]
Thank you Thiemo, now I understand and works :)

**Comment by dandan19793** [comment]
hi,

how do i rotate the axes of the camera? also, when i look at the axes, i think they are not aligned
 correctly as in marco's case, see pic attached (i am somehow lying on my left side).
![rviz](https://cloud.githubusercontent.com/assets/18536677/17781257/ed7a30a6-656e-11e6-9131-a47025d5c632.png)


thanks
