### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by liming0791** [code-iai/iai_kinect2#309]
when compiling, I got this error message:

```
/home/liming/catkin-ws/src/iai_kinect2/kinect2_viewer/src/viewer.cpp:32:44: fatal error: pcl/visualization/cloud_viewer.h: no such file or directory
 #include <pcl/visualization/cloud_viewer.h>
                                            ^
compilation terminated.
make[2]: *** [iai_kinect2/kinect2_viewer/CMakeFiles/kinect2_viewer.dir/src/viewer.cpp.o] error 1
make[1]: *** [iai_kinect2/kinect2_viewer/CMakeFiles/kinect2_viewer.dir/all] error 2
make: *** [all] error 2

```

I installed pcl by compiling the source code of pcl 1.7.2. I don't know what is wrong.

**Comment by wiedemeyer** [comment]
The PCL from the package repository should work fine. I can't really help with custom installations.
The only things I could suggest is to check if the header file exists on your PCL installation, maybe you didn't configured cmake correctly so that visualization is not build. Or try out 1.7.1 from source.
