### ISSUE TITLE
How to enable depth_registration?

### ISSUE THREAD

**Issue by TrinhTUHH** [code-iai/iai_kinect2#439]
I'm following this tutorial: http://wg-perception.github.io/tabletop/index.html#tabletop which using Object Recognition Kitchen (ORK) package to detect object. However when I run the command `rosrun rqt_reconfigure rqt_reconfigure` I don't see any camera on the GUI to enable the depth_registration as it should be. 
![image](https://user-images.githubusercontent.com/19979949/28921641-0fb39044-7857-11e7-97f1-d70d2e302ca0.png)
Do you know what is the problem?

**Comment by bbferka** [comment]
@TrinhTUHH your question has nothing to do with this package (ok, maybe it does a little, but I can not know because you don't say you are using a KinectOne). Anyway, these sort of questions should be asked from the maintainers of ORK. Btw, did you actually start the launch file of any camera?. Post your question on ROS discourse. I'm closing this (non-)issue.

**Comment by TrinhTUHH** [comment]
Hi, I did use this `roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true`
and the Kinect2 works ok with rviz. I just think that there may be some problem with this lib because there is no such problem with Kinect, so I just posted it here.

**Comment by bbferka** [comment]
Ah, ok, that makes more sense now :smile:  We don't offer a separate depth_registration flag for the kinect2.
